server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/auth/register {
        proxy_pass http://auth-service:8000/register;
    }

    location /api/auth/login {
        proxy_pass http://auth-service:8000/login;
    }

    location /api/auth/users {
        proxy_pass http://auth-service:8000/users;
    }

    location /api/products {
        proxy_pass http://product-service:8000/products;
    }

    location /api/orders {
        proxy_pass http://order-service:8000/orders;
    }

    location /api/chat {
        proxy_pass http://chat-service:8000/messages;
    }
}