events {}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:8000/;
        }

        location = /products {
            proxy_pass http://product-service:8000/products;
        }

        location /products/ {
            proxy_pass http://product-service:8000/products/;
        }

        location = /orders {
            proxy_pass http://order-service:8000/orders;
        }

        location /orders/ {
            proxy_pass http://order-service:8000/orders/;
        }

        location = /users {
            proxy_pass http://user-service:8000/users;
        }

        location /users/ {
            proxy_pass http://user-service:8000/users/;
        }

        location = /chat {
            proxy_pass http://chat-service:8000/messages;
        }

        location /chat/ {
            proxy_pass http://chat-service:8000/messages/;
        }
    }
}