events {}

http {
    upstream order_service_cluster {
        server order-service:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://order_service_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}